#!/bin/sh

set -eu

cd "$(dirname "$0")"
cd ..

if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
  echo "Not pushing for branch build." >&2
  exit
fi

BRANCH=gh-pages
REPO=$(git config remote.origin.url | sed s/^git:/https:/)

git config user.name "$GIT_NAME"
git config user.email "$GIT_EMAIL"
git config credential.helper "store --file=.git/credentials"
echo "https://${GH_TOKEN}:@github.com" >.git/credentials

git remote set-url --push origin "$REPO"
git remote set-branches --add origin "$BRANCH"

git fetch -q
git branch -f "$BRANCH" "origin/${BRANCH}"

./tools/buildpages

git push origin "${BRANCH}:${BRANCH}"
rm .git/credentials
